version: '3'

services:
  server:
    build: "./server"
    ports:
      - 8080:8080
    volumes:
      - "./server:/app"

  client:
    build: "./client"
    ports:
      - 5173:5173
    volumes:
      - "./client:/app"
