export const graph_constants = {
    line_stroke: '#aaa',
    line_stroke_width: 2,
    link_label_font_size: '20px',
    link_label_dx: -15,
    link_label_dy: -10,
    node_radius: 50,
    node_box_shadow: '0px 0px 5px #666',
    node_label_font_size: '25px',
    node_label_font_family: 'Roboto, sans-serif',
    node_label_dy: '0.35em',
    node_label_fill: 'white',
    node_label_text_shadow: '2px 2px 4px #666',
    node_gradient_0: '#4bded1',
    node_gradient_100: '#00baaa',
    visited_node_gradient_0: '#ff9999',
    visited_node_gradient_100: '#ff3333',
    start_node_gradient_0: '#b0e57c',
    start_node_gradient_100: '#45d045',
    end_node_gradient_0: '#ff9999',
    end_node_gradient_100: '#ff3333',
    simulation_charge_strength: -1000,
    simulation_collision_radius: 60,
    simulation_line_stepped_stroke: 'red',
    simulation_step_delta_time: 500,
    resize_width: 800,
    resize_height: 600,
};
